spring.profiles.active=dev

spring.datasource.username=postgres
spring.datasource.password=abcdefg
spring.datasource.url=jdbc:postgresql://localhost/wybory?reWriteBatchedInserts=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.enable_lazy_load_no_trans=true
spring.session.jdbc.initialize-schema=always
spring.jpa.open-in-view=false

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
logging.level.org.hibernate.SQL=INFO
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=INFO

org.slf4j.simpleLogger.defaultLogLevel = debug